[package]
name = "debate"
version = "1.0.0"
authors = []

[addresses]
debate = "0x18693562f4ced0fd77d6b42416003a5945d15358431fbff2b9af0e4b0759d261"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "aptos-cli-v2.5.0" }

[dev-dependencies]
